### ISSUE TITLE
Could we possibly have an option between CocoaPods and Regular framework?

### ISSUE THREAD

**Issue by kamathis4** [terrakok/Compose-Multiplatform-Wizard#11]
Thanks for this wonderful MPP generator.
Had a small request if you could possibly add the option of choosing in iOS between CocoaPods and Regular framework as well. 

I could possibly work on this as well, if you want

**Comment by terrakok** [comment]
Could you explain a reason for that? Why don't you want to use the cocoapods integration for building ios app?

**Comment by kamathis4** [comment]
Well, in the few experiences that I had with cocapods, had some issues with ruby versions, [gradle sync files deleted](https://github.com/icerockdev/moko-kswift/issues/68) and many such.

I understand that cocoapods is mobing towards the go-to and regular framework might just be the fallback, so if we want to have the option, that would be nice!!

**Comment by tscholze** [comment]
I would also highly recommend using regular frameworks or give the option.
CocoaPods is a heavy weight dependency manager that's too "much" for most of the apps.

It required the usage of a XCWorkspace.

I really hope, that JetBrains will bring local SPM package support.

**Comment by terrakok** [comment]
Have you tried the wizard? The issue is outdated already
