### ISSUE TITLE
Ktor and Coroutines versions are incompatible

### ISSUE THREAD

**Issue by MohamedRejeb** [terrakok/Compose-Multiplatform-Wizard#17]
I suggest to keep the version of coroutines at 1.6.4 because for now Ktor 2.3.0 and coroutines 1.7.1 doesn't work together, I think that we need to wait until a new Ktor update

https://youtrack.jetbrains.com/issue/KTOR-5728

**Comment by terrakok** [comment]
you are right! thank you!
will wait https://github.com/ktorio/ktor/pull/3609

**Comment by terrakok** [comment]
https://github.com/terrakok/Compose-Multiplatform-Wizard/commit/6c7deac9046bce99cb118f53567bc27936307a2f
