### ISSUE TITLE
Broken build with SQLDelight

### ISSUE THREAD

**Issue by jordond** [terrakok/Compose-Multiplatform-Wizard#19]
If you include SQLDelight then sync and build, I get the following error:

<img width="1200" alt="image" src="https://github.com/terrakok/Compose-Multiplatform-Wizard/assets/528792/faa18757-5a82-474e-9b5b-49555616b4f9">

Steps:

1. With all defaults, select SQLdelight
2. Download
3. Open in Android Studio
4. Sync & Build

**Comment by terrakok** [comment]
Thank you for the report! I'll fix it asap

**Comment by daniaviladomingo** [comment]
I haven't had any problem with this in my project https://github.com/daniaviladomingo/kmm

**Comment by terrakok** [comment]
The problem is in `build` command. it tries to build a whole project.

**Comment by terrakok** [comment]
It seems all works fine now
