### ISSUE TITLE
Add PreCompose as another option for navigation

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [terrakok/Compose-Multiplatform-Wizard#24]
First of all thanks a bunch for this wizard! It has made my life so much easier ⭐ It's great to see it growing both in features and popularity.

I can observe that the wizard has only one option for the navigation library (i.e. Voyage) whereas we can see there are multiple options for some other kinds of libraries (like DI that contains Koin and Kodein), therefore, here's another option for the `Navigation` category, it's called `PreCompose`:

https://github.com/Tlaster/PreCompose

It's perfect for users who are coming to KMP/CMP from the Android (Jetpack Compose) world, the API is very similar to Android thereby making the learning curve almost negligible.

Do consider checking it out and if it fits the description, then adding it in the wizard as well 👍

**Comment by terrakok** [comment]
Yes, it's good idea
