### ISSUE TITLE
Not compatible with Android Studio Giraffe

### ISSUE THREAD

**Issue by Mats-Hjalmar** [terrakok/Compose-Multiplatform-Wizard#27]
The AGP version is too high for Android Studio Giraffe. The current supported version is [8.1](https://developer.android.com/studio/releases#android_gradle_plugin_and_android_studio_compatibility) but the version provided in the wizard is 8.1.0-alpha04. It would be nice to have a drop down to select what Android Studio the user is using or possibly a checkbox for restricting to stable builds.

**Comment by terrakok** [comment]
I guess you are not right

https://github.com/terrakok/Compose-Multiplatform-Wizard/blob/79aa48ff2fa118fbb1d906c725a76f4ddce25195/src/commonMain/kotlin/wizard/Entity.kt#L19
