### ISSUE TITLE
commonMain - kotlin - package name - images/strings folder.

### ISSUE THREAD

**Issue by casontek** [terrakok/Compose-Multiplatform-Wizard#36]
### What is the use of directory images and string folder

public expect object ResImages gives error after opening it.

- any explanation on how to use image and other resource file

<img width="988" alt="Screenshot 2023-09-27 at 16 54 42" src="https://github.com/terrakok/Compose-Multiplatform-Wizard/assets/76940582/3adfd7e3-d60b-4c6b-8808-d65e165406a5">

**Comment by casontek** [comment]
I want to understand how to import and use image and other binary files in this KMM project.
And also the use of the above images/strings directories, ResImages/ResStrings kotlin files

**Comment by terrakok** [comment]
I don't see an issue related with the Web Wizard
