### ISSUE TITLE
Could not find "co.touchlab:stately-common"

### ISSUE THREAD

**Issue by hmshohrab** [terrakok/Compose-Multiplatform-Wizard#40]
i can't run on ios device from xcode... this error message are thrown.

Could not find "co.touchlab:stately-common" in [/Users/md.asifparvez/Shohrab/PureMind/Muslim, /Users/md.asifparvez/.konan/klib, /Users/md.asifparvez/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/common, /Users/md.asifparvez/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/platform/ios_simulator_arm64]

**Comment by terrakok** [comment]
could you provide a project to reproduce the issue?

**Comment by rkshnair** [comment]
Same for me as well. Simply create and download the project and try to run iOS emulator. This error is coming. Android working like a charm no issues.

**Comment by terrakok** [comment]
I don't see the problem. A new generated project works as expected.
send an reproducer, plz

**Comment by hmshohrab** [comment]
<img width="698" alt="Screenshot 2023-12-13 at 10 47 34 PM" src="https://github.com/terrakok/Compose-Multiplatform-Wizard/assets/47864478/06c2fef7-dac9-43bd-9a61-cbf8b4b2d8b4">

**Comment by terrakok** [comment]
This is not what I asked. I need a project

**Comment by hmshohrab** [comment]
implementation("co.touchlab:stately-common:2.0.6")
  When I added it, it worked fine.

**Comment by hmshohrab** [comment]
Can you help me to add cocoapods in this projects?

**Comment by terrakok** [comment]
I guess all the needed information is here: https://kotlinlang.org/docs/native-cocoapods-xcode.html
