### ISSUE TITLE
Libres dynamic image not loading in IOS app... 

### ISSUE THREAD

**Issue by hmshohrab** [terrakok/Compose-Multiplatform-Wizard#41]
Uncaught Kotlin exception: kotlin.IllegalStateException: LibresComposeApp.bundle not found
<img width="773" alt="Screenshot 2023-12-14 at 11 58 43 AM" src="https://github.com/terrakok/Compose-Multiplatform-Wizard/assets/47864478/e70c1ffa-63f0-4db0-abe1-5444c7289949">

**Comment by terrakok** [comment]
Are you sure that is the wizard problem?
