### ISSUE TITLE
Info.plist in iOS?

### ISSUE THREAD

**Issue by ShmuelSterbach-Cammebys** [terrakok/Compose-Multiplatform-Wizard#44]
I am trying to add Microsoft SSO login to my app, but it [requires editing](https://github.com/AzureAD/microsoft-authentication-library-for-objc?tab=readme-ov-file#configuring-msal) the Info.plist to add a redirect URL. There is no Info.plist in the iosApp folder generated by your amazing tool (that I use constantly). How can I accomplish this?

**Comment by terrakok** [comment]
Open an ios project in xcode and create any value there. Xcode will create the file

**Comment by ShmuelSterbach-Cammebys** [comment]
I get this error:
Multiple commands produce '/Users/shmueladmin/Library/Developer/Xcode/DerivedData/iosApp-emvlkobhvqnfhogrloztkzyoxuia/Build/Products/Debug-iphonesimulator/MyApp.app/Info.plist'

Target 'iosApp' (project 'iosApp') has copy command from '/Users/shmueladmin/KotlinMultiplatformProjects/MyApp/iosApp/Info.plist' to '/Users/shmueladmin/Library/Developer/Xcode/DerivedData/iosApp-emvlkobhvqnfhogrloztkzyoxuia/Build/Products/Debug-iphonesimulator/MyApp.app/Info.plist'
Target 'iosApp' (project 'iosApp') has process command with output '/Users/shmueladmin/Library/Developer/Xcode/DerivedData/iosApp-emvlkobhvqnfhogrloztkzyoxuia/Build/Products/Debug-iphonesimulator/MyApp.app/Info.plist'

**Comment by ShmuelSterbach-Cammebys** [comment]
(reference for future developers) If I add properties here it works (it created the Info.plist):
<img width="1624" alt="Screenshot 2024-01-16 at 1 28 28 PM" src="https://github.com/terrakok/Compose-Multiplatform-Wizard/assets/144174211/b6ac1dcf-602d-440e-ac83-d5c4d3686783">
