### ISSUE TITLE
Generated version of the Graddle Wrapper is outdated

### ISSUE THREAD

**Issue by illarionov** [terrakok/Compose-Multiplatform-Wizard#48]
When generating a project, Gradle version 8.7 is added to gradle.properties:
```properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip
```

But Gradle Wrapper files of some older version are used (*gradlew*, *gradlew.bat*, *gradle/wrapper/gradle-wrapper.jar*).
After generating the project, you need to manually run ` ./gradlew wrapper --gradle-version=8.7` to update the wrapper, it would be nice if it was updated when generated.

**Comment by terrakok** [comment]
done
