### ISSUE TITLE
@Preview not working

### ISSUE THREAD

**Issue by Lampotrias** [terrakok/Compose-Multiplatform-Wizard#55]
Hi

![Screenshot from 2024-05-14 10-58-36](https://github.com/terrakok/Compose-Multiplatform-Wizard/assets/4716451/1e914f33-4499-4d3c-abb0-864e3733c766)

I put code at generated project:
```
@Composable
@Preview(showBackground = true, showSystemUi = true)
fun Pr() {
    App()
}
```

in `App.android.kt`

when I open preview window i see error:
`org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: composeResources/multiplatform_app.composeapp.generated.resources/values/strings.commonMain.cvr   at _layoutlib_._internal_.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith   ... (ContinuationImpl.kt:33)   at _layoutlib_._internal_.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)   at _layoutlib_._internal_.kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)   at _layoutlib_._internal_.kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)   at _layoutlib_._internal_.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)   at _layoutlib_._internal_.kotlinx.coroutines.BuildersKt.runBlocking  at _layoutlib_._internal_.kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)   at _layoutlib_._internal_.kotlinx.coroutines.BuildersKt.runBlocking$default  at org.company.app.ComposableSingletons$AppKt$lambda-2$1.invoke   ... (App.kt:31)   at org.company.app.ComposableSingletons$AppKt$lambda-2$1.invoke(App.kt:22)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:134)   at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:115)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:112)   at org.company.app.theme.ThemeKt$AppTheme$1$1.invoke(Theme.kt:89)   at org.company.app.theme.ThemeKt$AppTheme$1$1.invoke(Theme.kt:89)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)   at androidx.compose.material3.TextKt.ProvideTextStyle(Text.kt:352)   at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:72)   at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:71)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:64)   at org.company.app.theme.ThemeKt$AppTheme$1.invoke(Theme.kt:87)   at org.company.app.theme.ThemeKt$AppTheme$1.invoke(Theme.kt:84)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)   at org.company.app.theme.ThemeKt.AppTheme(Theme.kt:82)   at org.company.app.AppKt.App(App.kt:22)   at org.company.app.App_androidKt.Pr(App.android.kt:45)   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)   at java.lang.reflect.Method.invoke(Method.java:568)   at androidx.compose.ui.tooling.ComposableInvoker.invokeComposableMethod(ComposableInvoker.jvm.kt:181)   at androidx.compose.ui.tooling.ComposableInvoker.invokeComposable(ComposableInvoker.jvm.kt:221)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3$1$composable$1.invoke(ComposeViewAdapter.android.kt:504)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3$1$composable$1.invoke(ComposeViewAdapter.android.kt:502)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3$1.invoke(ComposeViewAdapter.android.kt:539)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3$1.invoke(ComposeViewAdapter.android.kt:497)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at androidx.compose.ui.tooling.InspectableKt.Inspectable(Inspectable.android.kt:61)   at androidx.compose.ui.tooling.ComposeViewAdapter$WrapPreview$1.invoke(ComposeViewAdapter.android.kt:444)   at androidx.compose.ui.tooling.ComposeViewAdapter$WrapPreview$1.invoke(ComposeViewAdapter.android.kt:443)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at androidx.compose.ui.tooling.ComposeViewAdapter.WrapPreview(ComposeViewAdapter.android.kt:438)   at androidx.compose.ui.tooling.ComposeViewAdapter.access$WrapPreview(ComposeViewAdapter.android.kt:124)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3.invoke(ComposeViewAdapter.android.kt:497)   at androidx.compose.ui.tooling.ComposeViewAdapter$init$3.invoke(ComposeViewAdapter.android.kt:494)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)   at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)   at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:186)   at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)   at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)   at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:139)   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:138)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:138)   at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:123)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)   at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)   at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:90)   at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3302)   at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3235)   at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725)   at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1071)   at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)   at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619)   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:123)   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:114)   at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1289)   at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:114)   at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:164)   at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)   at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:121)   at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:114)   at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1364)   at android.view.View.dispatchAttachedToWindow(View.java:21980)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)   at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:44)`

How can I fix this problem?

Thanks

**Comment by terrakok** [comment]
Android Studio doesn't support compose multiplatform projects. Use new Fleet IDE: https://www.jetbrains.com/fleet/

**Comment by terrakok** [comment]
https://github.com/JetBrains/compose-multiplatform/issues/4476

**Comment by Lampotrias** [comment]
> Android Studio doesn't support compose multiplatform projects. Use new Fleet IDE: https://www.jetbrains.com/fleet/

Konstantin, thank you for your reply. I'll try!
