### ISSUE TITLE
Add Navigation Compose

### ISSUE THREAD

**Issue by Shahriyar13** [terrakok/Compose-Multiplatform-Wizard#62]
https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-navigation-routing.html

Adding Navigation Compose library 

Experimental navigation library﻿
The common navigation library, based on Jetpack Compose, is now available. For details, see the [documentation](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-navigation-routing.html).

**Comment by terrakok** [comment]
I don't see a reason to add this library when there are awesome Voyager and Decompose

**Comment by Shahriyar13** [comment]
Thank you for your response. While Voyager and Decompose are indeed excellent libraries, I believe that including the Navigation Compose library as an option would be beneficial for developers who prefer it. Providing a variety of choices allows developers to select the tools and libraries that best suit their needs and preferences. This flexibility can enhance the overall utility and appeal of the app wizard. Thank you for considering this suggestion.
